//! `oakum version` writes planned manifests, inherited pins, lockfile rows, and changelogs, then deletes consumed bump files.

#![allow(clippy::disallowed_methods)]

use std::fs;
use std::io::Write;
use std::path::PathBuf;
use std::process::{Command, Stdio};

fn bin() -> Command {
    Command::new(env!("CARGO_BIN_EXE_oakum"))
}

fn temp_repo(label: &str) -> PathBuf {
    let dir = PathBuf::from(env!("CARGO_TARGET_TMPDIR"))
        .join(format!("oakum-version-{label}-{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).expect("temp repo");
    fs::create_dir(dir.join(".git")).expect("fixture .git");
    dir
}

fn cargo_package(root: &std::path::Path, name: &str) {
    fs::write(
        root.join("Cargo.toml"),
        format!(
            "[package]\nname = \"{name}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[workspace]\n"
        ),
    )
    .expect("Cargo.toml");
    fs::create_dir_all(root.join("src")).expect("src");
    fs::write(root.join("src/lib.rs"), "").expect("lib.rs");
}

fn write_patch_changeset(root: &std::path::Path, name: &str) {
    fs::create_dir_all(root.join(".changeset")).expect("changeset");
    fs::write(
        root.join(".changeset/one.md"),
        format!("---\n{name}: patch\n---\n\npatch {name}\n"),
    )
    .expect("changeset");
}

fn inheriting_cargo_workspace(root: &std::path::Path, with_pin: bool) {
    fs::create_dir_all(root.join("crates/lib/src")).unwrap();
    fs::create_dir_all(root.join("crates/app/src")).unwrap();
    let pin = if with_pin {
        "[workspace.dependencies]\nlib = { path = \"crates/lib\", version = \"^0.1.0\" }\n"
    } else {
        ""
    };
    fs::write(
        root.join("Cargo.toml"),
        format!(
            "[workspace]\nresolver = \"2\"\nmembers = [\"crates/lib\", \"crates/app\"]\n[workspace.package]\nversion = \"0.1.0\"\n{pin}"
        ),
    )
    .unwrap();
    fs::write(
        root.join("crates/lib/Cargo.toml"),
        "[package]\nname = \"lib\"\nversion.workspace = true\nedition = \"2021\"\n",
    )
    .unwrap();
    fs::write(root.join("crates/lib/src/lib.rs"), "").unwrap();
    fs::write(
        root.join("crates/app/Cargo.toml"),
        "[package]\nname = \"app\"\nversion.workspace = true\nedition = \"2021\"\n",
    )
    .unwrap();
    fs::write(root.join("crates/app/src/lib.rs"), "").unwrap();
}

fn assert_consumed(root: &std::path::Path) {
    assert!(
        !root.join(".changeset/one.md").exists(),
        "consumed bump file should be deleted"
    );
}

fn assert_no_changelog(root: &std::path::Path) {
    assert!(
        !root.join("CHANGELOG.md").exists(),
        "empty or none plan should not write CHANGELOG.md"
    );
}

fn assert_changelog(path: &std::path::Path, version: &str, section: &str, note: &str) {
    let text = fs::read_to_string(path).unwrap_or_else(|err| panic!("{}: {err}", path.display()));
    let heading = format!("## {version} (");
    let Some(after_heading) = text.split_once(&heading).map(|(_, rest)| rest) else {
        panic!("{} should contain `{heading}`: {text}", path.display());
    };
    assert!(
        looks_like_ymd(&after_heading[..after_heading.len().min(10)]),
        "{} heading date should be YYYY-MM-DD: {text}",
        path.display()
    );
    let pinned = format!(
        "## {version} ({})\n\n### {section}\n\n{note}\n",
        &after_heading[..10]
    );
    assert!(
        text.contains(&pinned),
        "{} should contain `{pinned}`: {text}",
        path.display()
    );
    assert!(
        text.starts_with("# Changelog\n\n"),
        "{} should start with `# Changelog`: {text}",
        path.display()
    );
    assert!(
        text.contains("Generated by oakum 0.0.0.\n"),
        "{} should stamp the tool version: {text}",
        path.display()
    );
    assert!(
        !text.contains("<sub>"),
        "{} should not use HTML dates: {text}",
        path.display()
    );
    assert!(
        !text
            .lines()
            .any(|line| line.starts_with('_') && line.ends_with('_') && line.len() > 2),
        "{} should not use an italic-only date line: {text}",
        path.display()
    );
    assert!(
        !text.contains("\n\n\n"),
        "{} should not have extra blanks: {text}",
        path.display()
    );
    assert!(
        text.ends_with('\n') && !text.ends_with("\n\n"),
        "{} should end with one newline: {text:?}",
        path.display()
    );
}

fn looks_like_ymd(text: &str) -> bool {
    let bytes = text.as_bytes();
    bytes.len() == 10
        && bytes[4] == b'-'
        && bytes[7] == b'-'
        && bytes[0..4].iter().all(u8::is_ascii_digit)
        && bytes[5..7].iter().all(u8::is_ascii_digit)
        && bytes[8..10].iter().all(u8::is_ascii_digit)
}

#[test]
fn empty_plan_writes_nothing() {
    let root = temp_repo("empty");
    cargo_package(&root, "demo");
    let before = fs::read_to_string(root.join("Cargo.toml")).unwrap();

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(fs::read_to_string(root.join("Cargo.toml")).unwrap(), before);
    assert!(!root.join("Cargo.lock").exists());
    assert_no_changelog(&root);
}

#[test]
fn version_bumps_the_package_and_the_lockfile_row() {
    let root = temp_repo("bump-lock");
    cargo_package(&root, "demo");
    fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"demo\"\nversion = \"0.1.0\"\n",
    )
    .expect("lock");
    write_patch_changeset(&root, "demo");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let toml = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(toml.contains("version = \"0.1.1\""), "{toml}");
    let lock = fs::read_to_string(root.join("Cargo.lock")).unwrap();
    assert!(
        lock.contains("name = \"demo\"\nversion = \"0.1.1\""),
        "{lock}"
    );
    assert_consumed(&root);
    assert_changelog(&root.join("CHANGELOG.md"), "0.1.1", "Fixed", "patch demo");
}

#[test]
fn version_rewrites_workspace_table_and_member_version() {
    let root = temp_repo("inherit");
    fs::create_dir_all(root.join("crates/core/src")).unwrap();
    fs::create_dir_all(root.join("crates/app/src")).unwrap();
    fs::write(
        root.join("Cargo.toml"),
        "[workspace]\nresolver = \"2\"\nmembers = [\"crates/core\", \"crates/app\"]\n[workspace.dependencies]\ncore = { path = \"crates/core\", version = \"^0.1.0\" }\n",
    )
    .unwrap();
    fs::write(
        root.join("crates/core/Cargo.toml"),
        "[package]\nname = \"core\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    fs::write(root.join("crates/core/src/lib.rs"), "").unwrap();
    fs::write(
        root.join("crates/app/Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n[dependencies]\ncore = { workspace = true }\n",
    )
    .unwrap();
    fs::write(root.join("crates/app/src/lib.rs"), "").unwrap();
    fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"core\"\nversion = \"0.1.0\"\n\n[[package]]\nname = \"app\"\nversion = \"0.1.0\"\ndependencies = [\n \"core\",\n]\n",
    )
    .unwrap();
    write_patch_changeset(&root, "core");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let workspace = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(
        workspace.contains("core = { path = \"crates/core\", version = \"^0.1.1\" }"),
        "{workspace}"
    );
    let core = fs::read_to_string(root.join("crates/core/Cargo.toml")).unwrap();
    assert!(core.contains("version = \"0.1.1\""), "{core}");
    let app = fs::read_to_string(root.join("crates/app/Cargo.toml")).unwrap();
    assert!(app.contains("core = { workspace = true }"), "{app}");
    assert!(app.contains("version = \"0.1.0\""), "{app}");
    let lock = fs::read_to_string(root.join("Cargo.lock")).unwrap();
    assert!(
        lock.contains("name = \"core\"\nversion = \"0.1.1\""),
        "{lock}"
    );
    assert_consumed(&root);
    assert_changelog(
        &root.join("crates/core/CHANGELOG.md"),
        "0.1.1",
        "Fixed",
        "patch core",
    );
    assert!(!root.join("CHANGELOG.md").exists());
    assert!(!root.join("crates/app/CHANGELOG.md").exists());
}

#[test]
fn version_rewrites_package_and_workspace_table_in_the_same_file() {
    let root = temp_repo("pkg-ws-root");
    fs::create_dir_all(root.join("src")).unwrap();
    fs::create_dir_all(root.join("app/src")).unwrap();
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"core\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[workspace]\nresolver = \"2\"\nmembers = [\".\", \"app\"]\n[workspace.dependencies]\ncore = { path = \".\", version = \"^0.1.0\" }\n",
    )
    .unwrap();
    fs::write(root.join("src/lib.rs"), "").unwrap();
    fs::write(
        root.join("app/Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n[dependencies]\ncore = { workspace = true }\n",
    )
    .unwrap();
    fs::write(root.join("app/src/lib.rs"), "").unwrap();
    write_patch_changeset(&root, "core");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let toml = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(toml.contains("version = \"0.1.1\""), "{toml}");
    assert!(
        toml.contains("core = { path = \".\", version = \"^0.1.1\" }"),
        "{toml}"
    );
    assert_consumed(&root);
    assert_changelog(&root.join("CHANGELOG.md"), "0.1.1", "Fixed", "patch core");
}

#[test]
fn version_bumps_workspace_inherited_package_version() {
    let root = temp_repo("ws-pkg-ver");
    fs::create_dir_all(root.join("crates/demo/src")).unwrap();
    fs::write(
        root.join("Cargo.toml"),
        "[workspace]\nresolver = \"2\"\nmembers = [\"crates/demo\"]\n[workspace.package]\nversion = \"0.1.0\"\n",
    )
    .unwrap();
    fs::write(
        root.join("crates/demo/Cargo.toml"),
        "[package]\nname = \"demo\"\nversion.workspace = true\nedition = \"2021\"\n",
    )
    .unwrap();
    fs::write(root.join("crates/demo/src/lib.rs"), "").unwrap();
    write_patch_changeset(&root, "demo");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let workspace = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(
        workspace.contains("[workspace.package]\nversion = \"0.1.1\""),
        "{workspace}"
    );
    let member = fs::read_to_string(root.join("crates/demo/Cargo.toml")).unwrap();
    assert!(member.contains("version.workspace = true"), "{member}");
    assert!(!member.contains("version = \"0.1.1\""), "{member}");
    assert_consumed(&root);
    assert_changelog(
        &root.join("crates/demo/CHANGELOG.md"),
        "0.1.1",
        "Fixed",
        "patch demo",
    );
}

#[test]
fn version_folds_workspace_package_version_with_a_pin_on_the_same_file() {
    let root = temp_repo("ws-pkg-pin");
    fs::create_dir_all(root.join("src")).unwrap();
    fs::create_dir_all(root.join("app/src")).unwrap();
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"core\"\nversion.workspace = true\nedition = \"2021\"\n\n[workspace]\nresolver = \"2\"\nmembers = [\".\", \"app\"]\n[workspace.package]\nversion = \"0.1.0\"\n[workspace.dependencies]\ncore = { path = \".\", version = \"^0.1.0\" }\n",
    )
    .unwrap();
    fs::write(root.join("src/lib.rs"), "").unwrap();
    fs::write(
        root.join("app/Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n[dependencies]\ncore = { workspace = true }\n",
    )
    .unwrap();
    fs::write(root.join("app/src/lib.rs"), "").unwrap();
    write_patch_changeset(&root, "core");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let toml = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(toml.contains("version.workspace = true"), "{toml}");
    assert!(
        toml.contains("[workspace.package]\nversion = \"0.1.1\""),
        "{toml}"
    );
    assert!(
        toml.contains("core = { path = \".\", version = \"^0.1.1\" }"),
        "{toml}"
    );
    assert_consumed(&root);
    assert_changelog(&root.join("CHANGELOG.md"), "0.1.1", "Fixed", "patch core");
}

#[test]
fn version_folds_workspace_package_version_with_a_pin_on_a_virtual_root() {
    let root = temp_repo("ws-pkg-virtual-pin");
    inheriting_cargo_workspace(&root, true);
    fs::write(
        root.join("crates/app/Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n[dependencies]\nlib = { workspace = true }\n",
    )
    .unwrap();
    write_patch_changeset(&root, "lib");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let workspace = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(
        workspace.contains("[workspace.package]\nversion = \"0.1.1\""),
        "{workspace}"
    );
    assert!(
        workspace.contains("lib = { path = \"crates/lib\", version = \"^0.1.1\" }"),
        "{workspace}"
    );
    let lib = fs::read_to_string(root.join("crates/lib/Cargo.toml")).unwrap();
    assert!(lib.contains("version.workspace = true"), "{lib}");
    assert_consumed(&root);
    assert_changelog(
        &root.join("crates/lib/CHANGELOG.md"),
        "0.1.1",
        "Fixed",
        "patch lib",
    );
    assert!(!root.join("CHANGELOG.md").exists());
}

#[test]
fn version_bumps_two_inheritors_that_share_the_workspace_version() {
    let root = temp_repo("ws-pkg-two");
    inheriting_cargo_workspace(&root, false);
    fs::create_dir_all(root.join(".changeset")).unwrap();
    fs::write(
        root.join(".changeset/one.md"),
        "---\nlib: patch\napp: patch\n---\n\npatch both\n",
    )
    .unwrap();

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let workspace = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(
        workspace.contains("[workspace.package]\nversion = \"0.1.1\""),
        "{workspace}"
    );
    assert_consumed(&root);
    assert_changelog(
        &root.join("crates/lib/CHANGELOG.md"),
        "0.1.1",
        "Fixed",
        "patch both",
    );
    assert_changelog(
        &root.join("crates/app/CHANGELOG.md"),
        "0.1.1",
        "Fixed",
        "patch both",
    );
}

#[test]
fn version_refuses_inheritors_that_need_different_workspace_versions() {
    let root = temp_repo("ws-pkg-conflict");
    inheriting_cargo_workspace(&root, false);
    let before = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    fs::create_dir_all(root.join(".changeset")).unwrap();
    fs::write(
        root.join(".changeset/one.md"),
        "---\nlib: patch\napp: minor\n---\n\nmixed\n",
    )
    .unwrap();

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        !output.status.success(),
        "expected inheritor conflict: {}",
        String::from_utf8_lossy(&output.stdout)
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("inherits [workspace.package].version"),
        "{stderr}"
    );
    assert_eq!(fs::read_to_string(root.join("Cargo.toml")).unwrap(), before);
    assert!(root.join(".changeset/one.md").exists());
    assert_no_changelog(&root);
}

#[test]
fn version_refuses_an_unplanned_inheritor_of_the_workspace_version() {
    let root = temp_repo("ws-pkg-sibling");
    inheriting_cargo_workspace(&root, false);
    let before = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"app\"\nversion = \"0.1.0\"\n\n[[package]]\nname = \"lib\"\nversion = \"0.1.0\"\n",
    )
    .unwrap();
    write_patch_changeset(&root, "lib");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        !output.status.success(),
        "expected unplanned inheritor: {}",
        String::from_utf8_lossy(&output.stdout)
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("app inherits [workspace.package].version and is not in the plan"),
        "{stderr}"
    );
    assert_eq!(fs::read_to_string(root.join("Cargo.toml")).unwrap(), before);
    let lock = fs::read_to_string(root.join("Cargo.lock")).unwrap();
    assert!(
        lock.contains("name = \"app\"\nversion = \"0.1.0\""),
        "{lock}"
    );
    assert!(
        lock.contains("name = \"lib\"\nversion = \"0.1.0\""),
        "{lock}"
    );
    assert!(root.join(".changeset/one.md").exists());
    assert!(!root.join("crates/lib/CHANGELOG.md").exists());
    assert!(!root.join("crates/app/CHANGELOG.md").exists());
}

#[test]
fn version_retargets_a_published_range_on_the_dependent() {
    let root = temp_repo("published-range");
    fs::create_dir_all(root.join("crates/core/src")).unwrap();
    fs::create_dir_all(root.join("crates/app/src")).unwrap();
    fs::write(
        root.join("Cargo.toml"),
        "[workspace]\nresolver = \"2\"\nmembers = [\"crates/core\", \"crates/app\"]\n",
    )
    .unwrap();
    fs::write(
        root.join("crates/core/Cargo.toml"),
        "[package]\nname = \"core\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    fs::write(root.join("crates/core/src/lib.rs"), "").unwrap();
    fs::write(
        root.join("crates/app/Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n[dependencies]\ncore = { path = \"../core\", version = \"^0.1.0\" }\n",
    )
    .unwrap();
    fs::write(root.join("crates/app/src/lib.rs"), "").unwrap();
    write_patch_changeset(&root, "core");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let app = fs::read_to_string(root.join("crates/app/Cargo.toml")).unwrap();
    assert!(
        app.contains("core = { path = \"../core\", version = \"^0.1.1\" }"),
        "{app}"
    );
    assert!(app.contains("version = \"0.1.0\""), "{app}");
    assert_consumed(&root);
    assert_changelog(
        &root.join("crates/core/CHANGELOG.md"),
        "0.1.1",
        "Fixed",
        "patch core",
    );
    assert!(!root.join("crates/app/CHANGELOG.md").exists());
}

#[test]
fn unretargetable_lockfile_leaves_manifests_untouched() {
    let root = temp_repo("bad-lock");
    cargo_package(&root, "demo");
    let before = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\npackage = 4\n",
    )
    .expect("lock");
    write_patch_changeset(&root, "demo");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        !output.status.success(),
        "expected lock retarget to fail: {}",
        String::from_utf8_lossy(&output.stdout)
    );
    assert_eq!(fs::read_to_string(root.join("Cargo.toml")).unwrap(), before);
    assert_eq!(
        fs::read_to_string(root.join("Cargo.lock")).unwrap(),
        "# This file is automatically @generated by Cargo.\nversion = 4\npackage = 4\n"
    );
    assert!(root.join(".changeset/one.md").exists());
    assert_no_changelog(&root);
}

#[test]
fn version_bumps_an_npm_package_json() {
    let root = temp_repo("npm");
    fs::write(
        root.join("package.json"),
        "{\n  \"name\": \"demo\",\n  \"version\": \"0.1.0\"\n}\n",
    )
    .expect("package.json");
    write_patch_changeset(&root, "demo");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let json = fs::read_to_string(root.join("package.json")).unwrap();
    assert!(json.contains("\"version\": \"0.1.1\""), "{json}");
    assert_consumed(&root);
    assert_changelog(&root.join("CHANGELOG.md"), "0.1.1", "Fixed", "patch demo");
}

#[test]
fn version_retargets_the_cargo_lock_under_the_workspace_root() {
    let root = temp_repo("nested-lock");
    let rust = root.join("rust");
    fs::create_dir_all(&rust).expect("rust");
    cargo_package(&rust, "demo");
    fs::write(
        rust.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"demo\"\nversion = \"0.1.0\"\n",
    )
    .expect("lock");
    fs::write(
        root.join("Cargo.lock"),
        "# decoy\nversion = 4\n\n[[package]]\nname = \"demo\"\nversion = \"9.9.9\"\n",
    )
    .expect("decoy");
    write_patch_changeset(&root, "demo");

    let output = bin()
        .current_dir(&rust)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let lock = fs::read_to_string(rust.join("Cargo.lock")).unwrap();
    assert!(
        lock.contains("name = \"demo\"\nversion = \"0.1.1\""),
        "{lock}"
    );
    let decoy = fs::read_to_string(root.join("Cargo.lock")).unwrap();
    assert!(decoy.contains("version = \"9.9.9\""), "{decoy}");
    assert_consumed(&root);
    assert_changelog(&rust.join("CHANGELOG.md"), "0.1.1", "Fixed", "patch demo");
    assert!(!root.join("CHANGELOG.md").exists());
}

#[test]
fn version_bumps_a_nested_npm_package_json() {
    let root = temp_repo("nested-npm");
    let pkg = root.join("packages/demo");
    fs::create_dir_all(&pkg).expect("packages/demo");
    fs::write(
        pkg.join("package.json"),
        "{\n  \"name\": \"demo\",\n  \"version\": \"0.1.0\"\n}\n",
    )
    .expect("package.json");
    fs::write(
        root.join("package.json"),
        "{\n  \"name\": \"decoy\",\n  \"version\": \"9.9.9\"\n}\n",
    )
    .expect("decoy");
    write_patch_changeset(&root, "demo");

    let output = bin()
        .current_dir(&pkg)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let json = fs::read_to_string(pkg.join("package.json")).unwrap();
    assert!(json.contains("\"version\": \"0.1.1\""), "{json}");
    let decoy = fs::read_to_string(root.join("package.json")).unwrap();
    assert!(decoy.contains("\"version\": \"9.9.9\""), "{decoy}");
    assert_consumed(&root);
    assert_changelog(&pkg.join("CHANGELOG.md"), "0.1.1", "Fixed", "patch demo");
    assert!(!root.join("CHANGELOG.md").exists());
}

#[test]
fn second_version_run_does_not_bump_again() {
    let root = temp_repo("twice");
    cargo_package(&root, "demo");
    write_patch_changeset(&root, "demo");

    let first = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        first.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&first.stderr)
    );
    assert_consumed(&root);
    let first_log = fs::read_to_string(root.join("CHANGELOG.md")).unwrap();
    assert_changelog(&root.join("CHANGELOG.md"), "0.1.1", "Fixed", "patch demo");

    let second = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        second.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&second.stderr)
    );
    let toml = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(toml.contains("version = \"0.1.1\""), "{toml}");
    assert!(!toml.contains("version = \"0.1.2\""), "{toml}");
    assert_eq!(
        fs::read_to_string(root.join("CHANGELOG.md")).unwrap(),
        first_log
    );
}

#[test]
fn none_bump_file_is_consumed_and_writes_nothing() {
    let root = temp_repo("none");
    cargo_package(&root, "demo");
    let before = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    fs::create_dir_all(root.join(".changeset")).unwrap();
    fs::write(
        root.join(".changeset/one.md"),
        "---\ndemo: none\n---\n\nno release\n",
    )
    .unwrap();

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(fs::read_to_string(root.join("Cargo.toml")).unwrap(), before);
    assert_consumed(&root);
    assert_no_changelog(&root);
}

#[test]
fn version_consumes_every_loaded_bump_file() {
    let root = temp_repo("two-files");
    cargo_package(&root, "demo");
    write_patch_changeset(&root, "demo");
    fs::write(
        root.join(".changeset/two.md"),
        "---\ndemo: minor\n---\n\nminor demo\n",
    )
    .unwrap();

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let toml = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(toml.contains("version = \"0.2.0\""), "{toml}");
    assert_consumed(&root);
    assert!(
        !root.join(".changeset/two.md").exists(),
        "second consumed bump file should be deleted"
    );
    assert_changelog(&root.join("CHANGELOG.md"), "0.2.0", "Added", "minor demo");
    let log = fs::read_to_string(root.join("CHANGELOG.md")).unwrap();
    assert!(log.contains("### Fixed\n\npatch demo\n"), "{log}");
}

#[test]
fn version_leaves_instruction_and_malformed_bump_files() {
    let root = temp_repo("skip-files");
    cargo_package(&root, "demo");
    write_patch_changeset(&root, "demo");
    fs::write(root.join(".changeset/README.md"), "keep\n").unwrap();
    fs::write(root.join(".changeset/bad.md"), "not a changeset\n").unwrap();

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_consumed(&root);
    assert_eq!(
        fs::read_to_string(root.join(".changeset/README.md")).unwrap(),
        "keep\n"
    );
    assert_eq!(
        fs::read_to_string(root.join(".changeset/bad.md")).unwrap(),
        "not a changeset\n"
    );
    assert_changelog(&root.join("CHANGELOG.md"), "0.1.1", "Fixed", "patch demo");
}

#[test]
fn version_prepends_a_section_onto_an_existing_changelog() {
    let root = temp_repo("changelog-prepend");
    cargo_package(&root, "demo");
    fs::write(
        root.join("CHANGELOG.md"),
        "# Changelog\n\n## [Unreleased]\n\n## 0.1.0 (2026-01-01)\n\n### Added\n\nold\n",
    )
    .unwrap();
    write_patch_changeset(&root, "demo");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_changelog(&root.join("CHANGELOG.md"), "0.1.1", "Fixed", "patch demo");
    let log = fs::read_to_string(root.join("CHANGELOG.md")).unwrap();
    assert!(log.contains("## [Unreleased]\n"), "{log}");
    assert!(
        log.contains("## 0.1.0 (2026-01-01)\n\n### Added\n\nold\n"),
        "{log}"
    );
    assert_consumed(&root);
}

#[test]
fn version_refuses_a_changelog_without_the_title() {
    let root = temp_repo("changelog-refuse");
    cargo_package(&root, "demo");
    let before = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    fs::write(root.join("CHANGELOG.md"), "notes\n").unwrap();
    write_patch_changeset(&root, "demo");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        !output.status.success(),
        "expected refuse: {}",
        String::from_utf8_lossy(&output.stdout)
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(
        stderr.contains("CHANGELOG.md does not start with `# Changelog`"),
        "{stderr}"
    );
    assert_eq!(fs::read_to_string(root.join("Cargo.toml")).unwrap(), before);
    assert_eq!(
        fs::read_to_string(root.join("CHANGELOG.md")).unwrap(),
        "notes\n"
    );
    assert!(root.join(".changeset/one.md").exists());
}

#[test]
fn version_refuses_a_changelog_with_a_bom() {
    let root = temp_repo("changelog-bom");
    cargo_package(&root, "demo");
    let before = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    fs::write(root.join("CHANGELOG.md"), "\u{FEFF}# Changelog\n").unwrap();
    write_patch_changeset(&root, "demo");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        !output.status.success(),
        "expected refuse: {}",
        String::from_utf8_lossy(&output.stdout)
    );
    let stderr = String::from_utf8_lossy(&output.stderr);
    assert!(stderr.contains("BOM"), "{stderr}");
    assert_eq!(fs::read_to_string(root.join("Cargo.toml")).unwrap(), before);
    assert_eq!(
        fs::read_to_string(root.join("CHANGELOG.md")).unwrap(),
        "\u{FEFF}# Changelog\n"
    );
    assert!(root.join(".changeset/one.md").exists());
}

#[test]
fn version_renders_a_configured_changelog_template() {
    let root = temp_repo("changelog-template");
    cargo_package(&root, "demo");
    fs::create_dir_all(root.join(".changeset")).unwrap();
    fs::write(
        root.join(".changeset/_config.toml"),
        "tool-version = \"0.0.0\"\ntemplate = \"## {{ version }} ({{ date }})\\n\\n{{ notes[0] }}\\n\"\n",
    )
    .unwrap();
    write_patch_changeset(&root, "demo");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let log = fs::read_to_string(root.join("CHANGELOG.md")).unwrap();
    assert!(log.starts_with("# Changelog\n\n## 0.1.1 ("), "{log}");
    assert!(log.contains(")\n\npatch demo\n"), "{log}");
    assert!(!log.contains("### Fixed"), "{log}");
    assert!(log.contains("Generated by oakum 0.0.0.\n"), "{log}");
    assert_consumed(&root);
}

#[test]
fn version_renders_a_changelog_template_file() {
    let root = temp_repo("changelog-template-file");
    cargo_package(&root, "demo");
    fs::create_dir_all(root.join(".changeset")).unwrap();
    fs::write(
        root.join("notes.md"),
        "## {{ version }} ({{ date }})\n\n{{ notes[0] }}\n",
    )
    .unwrap();
    fs::write(
        root.join(".changeset/_config.toml"),
        "tool-version = \"0.0.0\"\ntemplate = { file = \"notes.md\" }\n",
    )
    .unwrap();
    write_patch_changeset(&root, "demo");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let log = fs::read_to_string(root.join("CHANGELOG.md")).unwrap();
    assert!(log.starts_with("# Changelog\n\n## 0.1.1 ("), "{log}");
    assert!(log.contains(")\n\npatch demo\n"), "{log}");
    assert!(!log.contains("### Fixed"), "{log}");
    assert!(log.contains("Generated by oakum 0.0.0.\n"), "{log}");
    assert_consumed(&root);
}

#[test]
fn version_uses_notes_file_instead_of_bump_notes() {
    let root = temp_repo("notes-file");
    cargo_package(&root, "demo");
    write_patch_changeset(&root, "demo");
    fs::write(root.join("release-notes.md"), "workflow notes\n").unwrap();

    let output = bin()
        .current_dir(&root)
        .args(["version", "--notes-file", "release-notes.md"])
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let log = fs::read_to_string(root.join("CHANGELOG.md")).unwrap();
    assert!(log.starts_with("# Changelog\n\n## 0.1.1 ("), "{log}");
    assert!(log.contains(")\n\nworkflow notes\n"), "{log}");
    assert!(!log.contains("patch demo"), "{log}");
    assert!(!log.contains("### Fixed"), "{log}");
    assert_consumed(&root);
}

#[test]
fn version_keeps_leading_blank_lines_from_notes_file() {
    let root = temp_repo("notes-leading-blanks");
    cargo_package(&root, "demo");
    write_patch_changeset(&root, "demo");
    fs::write(root.join("release-notes.md"), "\n\nworkflow notes\n").unwrap();

    let output = bin()
        .current_dir(&root)
        .args(["version", "--notes-file", "release-notes.md"])
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let log = fs::read_to_string(root.join("CHANGELOG.md")).unwrap();
    assert!(log.contains(")\n\n\n\nworkflow notes\n"), "{log}");
    assert_consumed(&root);
}

#[test]
fn version_reads_notes_from_stdin() {
    let root = temp_repo("notes-stdin");
    cargo_package(&root, "demo");
    write_patch_changeset(&root, "demo");

    let mut child = bin()
        .current_dir(&root)
        .args(["version", "--notes-file", "-"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn");
    child
        .stdin
        .as_mut()
        .expect("stdin")
        .write_all(b"piped notes\n")
        .expect("write");
    let output = child.wait_with_output().expect("wait");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let log = fs::read_to_string(root.join("CHANGELOG.md")).unwrap();
    assert!(log.contains(")\n\npiped notes\n"), "{log}");
    assert!(!log.contains("patch demo"), "{log}");
    assert_consumed(&root);
}

#[test]
fn version_strips_bom_from_stdin_notes() {
    let root = temp_repo("notes-stdin-bom");
    cargo_package(&root, "demo");
    write_patch_changeset(&root, "demo");

    let mut child = bin()
        .current_dir(&root)
        .args(["version", "--notes-file", "-"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn");
    child
        .stdin
        .as_mut()
        .expect("stdin")
        .write_all("\u{FEFF}piped notes\n".as_bytes())
        .expect("write");
    let output = child.wait_with_output().expect("wait");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let log = fs::read_to_string(root.join("CHANGELOG.md")).unwrap();
    assert!(log.contains(")\n\npiped notes\n"), "{log}");
    assert!(!log.contains('\u{FEFF}'), "{log}");
    assert_consumed(&root);
}

#[test]
fn version_refuses_empty_stdin_notes() {
    let root = temp_repo("notes-stdin-empty");
    cargo_package(&root, "demo");
    write_patch_changeset(&root, "demo");

    let mut child = bin()
        .current_dir(&root)
        .args(["version", "--notes-file", "-"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn");
    drop(child.stdin.take());
    let output = child.wait_with_output().expect("wait");
    assert!(!output.status.success());
    let err = String::from_utf8_lossy(&output.stderr);
    assert!(err.contains("`--notes-file -` produced no notes"), "{err}");
    assert!(!root.join("CHANGELOG.md").exists());
    assert!(root.join(".changeset/one.md").exists());
}

#[test]
fn version_refuses_newline_only_stdin_notes() {
    let root = temp_repo("notes-stdin-newline");
    cargo_package(&root, "demo");
    write_patch_changeset(&root, "demo");

    let mut child = bin()
        .current_dir(&root)
        .args(["version", "--notes-file", "-"])
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn");
    child
        .stdin
        .as_mut()
        .expect("stdin")
        .write_all(b"\n")
        .expect("write");
    let output = child.wait_with_output().expect("wait");
    assert!(!output.status.success());
    let err = String::from_utf8_lossy(&output.stderr);
    assert!(err.contains("`--notes-file -` produced no notes"), "{err}");
    assert!(!root.join("CHANGELOG.md").exists());
    assert!(root.join(".changeset/one.md").exists());
}

#[test]
fn version_does_not_read_stdin_without_notes_file() {
    let root = temp_repo("notes-no-stdin");
    cargo_package(&root, "demo");
    write_patch_changeset(&root, "demo");

    let mut child = bin()
        .current_dir(&root)
        .arg("version")
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("spawn");
    child
        .stdin
        .as_mut()
        .expect("stdin")
        .write_all(b"should ignore\n")
        .expect("write");
    let output = child.wait_with_output().expect("wait");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let log = fs::read_to_string(root.join("CHANGELOG.md")).unwrap();
    assert!(log.contains("### Fixed\n\npatch demo\n"), "{log}");
    assert!(!log.contains("should ignore"), "{log}");
    assert_consumed(&root);
}

#[test]
fn version_empty_notes_file_writes_heading_only() {
    let root = temp_repo("notes-empty");
    cargo_package(&root, "demo");
    write_patch_changeset(&root, "demo");
    fs::write(root.join("release-notes.md"), "").unwrap();

    let output = bin()
        .current_dir(&root)
        .args(["version", "--notes-file", "release-notes.md"])
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let log = fs::read_to_string(root.join("CHANGELOG.md")).unwrap();
    assert!(log.contains("## 0.1.1 ("), "{log}");
    assert!(!log.contains("patch demo"), "{log}");
    assert!(!log.contains("### "), "{log}");
    assert_consumed(&root);
}

#[test]
fn version_strips_bom_from_notes_file() {
    let root = temp_repo("notes-bom");
    cargo_package(&root, "demo");
    write_patch_changeset(&root, "demo");
    fs::write(root.join("release-notes.md"), "\u{FEFF}workflow notes\n").unwrap();

    let output = bin()
        .current_dir(&root)
        .args(["version", "--notes-file", "release-notes.md"])
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let log = fs::read_to_string(root.join("CHANGELOG.md")).unwrap();
    assert!(log.contains(")\n\nworkflow notes\n"), "{log}");
    assert!(!log.contains('\u{FEFF}'), "{log}");
    assert_consumed(&root);
}

#[test]
fn version_refuses_a_notes_file_outside_the_repo() {
    let root = temp_repo("notes-escape");
    cargo_package(&root, "demo");
    write_patch_changeset(&root, "demo");

    let output = bin()
        .current_dir(&root)
        .args(["version", "--notes-file", "../secret.md"])
        .output()
        .expect("run");
    assert!(!output.status.success());
    let err = String::from_utf8_lossy(&output.stderr);
    assert!(err.contains("failed to resolve --notes-file"), "{err}");
    assert!(err.contains("outside the repository"), "{err}");
    assert!(!err.contains("template"), "{err}");
    assert!(!root.join("CHANGELOG.md").exists());
    assert!(root.join(".changeset/one.md").exists());
}

#[test]
fn version_refuses_a_missing_notes_file() {
    let root = temp_repo("notes-missing");
    cargo_package(&root, "demo");
    write_patch_changeset(&root, "demo");

    let output = bin()
        .current_dir(&root)
        .args(["version", "--notes-file", "release-notes.md"])
        .output()
        .expect("run");
    assert!(!output.status.success());
    let err = String::from_utf8_lossy(&output.stderr);
    assert!(err.contains("failed to resolve --notes-file"), "{err}");
    assert!(!err.contains("template"), "{err}");
    assert!(!root.join("CHANGELOG.md").exists());
    assert!(root.join(".changeset/one.md").exists());
}

#[test]
fn version_renders_notes_file_through_a_template() {
    let root = temp_repo("notes-template");
    cargo_package(&root, "demo");
    fs::create_dir_all(root.join(".changeset")).unwrap();
    fs::write(
        root.join(".changeset/_config.toml"),
        "tool-version = \"0.0.0\"\ntemplate = \"## {{ version }} ({{ date }})\\n\\n{{ notes[0] }}\\n\"\n",
    )
    .unwrap();
    write_patch_changeset(&root, "demo");
    fs::write(root.join("release-notes.md"), "templated notes\n").unwrap();

    let output = bin()
        .current_dir(&root)
        .args(["version", "--notes-file", "release-notes.md"])
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let log = fs::read_to_string(root.join("CHANGELOG.md")).unwrap();
    assert!(log.contains(")\n\ntemplated notes\n"), "{log}");
    assert!(!log.contains("patch demo"), "{log}");
    assert_consumed(&root);
}

#[test]
fn tool_version_mismatch_refuses() {
    let root = temp_repo("toolver");
    cargo_package(&root, "demo");
    fs::create_dir_all(root.join(".changeset")).expect("dir");
    fs::write(
        root.join(".changeset/_config.toml"),
        "tool-version = \"9.9.9\"\n",
    )
    .expect("config");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(!output.status.success());
    let err = String::from_utf8_lossy(&output.stderr);
    assert!(
        err.contains("tool-version") && err.contains("upgrade"),
        "stderr: {err}"
    );
}
