//! `oakum version` writes planned manifests, inherited pins, and lockfile rows.

#![allow(clippy::disallowed_methods)]

use std::fs;
use std::path::PathBuf;
use std::process::Command;

fn bin() -> Command {
    Command::new(env!("CARGO_BIN_EXE_oakum"))
}

fn temp_repo(label: &str) -> PathBuf {
    let dir = PathBuf::from(env!("CARGO_TARGET_TMPDIR"))
        .join(format!("oakum-version-{label}-{}", std::process::id()));
    let _ = fs::remove_dir_all(&dir);
    fs::create_dir_all(&dir).expect("temp repo");
    fs::create_dir(dir.join(".git")).expect("fixture .git");
    dir
}

fn cargo_package(root: &std::path::Path, name: &str) {
    fs::write(
        root.join("Cargo.toml"),
        format!(
            "[package]\nname = \"{name}\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[workspace]\n"
        ),
    )
    .expect("Cargo.toml");
    fs::create_dir_all(root.join("src")).expect("src");
    fs::write(root.join("src/lib.rs"), "").expect("lib.rs");
}

fn write_patch_changeset(root: &std::path::Path, name: &str) {
    fs::create_dir_all(root.join(".changeset")).expect("changeset");
    fs::write(
        root.join(".changeset/one.md"),
        format!("---\n{name}: patch\n---\n\npatch {name}\n"),
    )
    .expect("changeset");
}

#[test]
fn empty_plan_writes_nothing() {
    let root = temp_repo("empty");
    cargo_package(&root, "demo");
    let before = fs::read_to_string(root.join("Cargo.toml")).unwrap();

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    assert_eq!(fs::read_to_string(root.join("Cargo.toml")).unwrap(), before);
    assert!(!root.join("Cargo.lock").exists());
}

#[test]
fn version_bumps_the_package_and_the_lockfile_row() {
    let root = temp_repo("bump-lock");
    cargo_package(&root, "demo");
    fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"demo\"\nversion = \"0.1.0\"\n",
    )
    .expect("lock");
    write_patch_changeset(&root, "demo");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let toml = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(toml.contains("version = \"0.1.1\""), "{toml}");
    let lock = fs::read_to_string(root.join("Cargo.lock")).unwrap();
    assert!(
        lock.contains("name = \"demo\"\nversion = \"0.1.1\""),
        "{lock}"
    );
}

#[test]
fn version_rewrites_workspace_table_and_member_version() {
    let root = temp_repo("inherit");
    fs::create_dir_all(root.join("crates/core/src")).unwrap();
    fs::create_dir_all(root.join("crates/app/src")).unwrap();
    fs::write(
        root.join("Cargo.toml"),
        "[workspace]\nresolver = \"2\"\nmembers = [\"crates/core\", \"crates/app\"]\n[workspace.dependencies]\ncore = { path = \"crates/core\", version = \"^0.1.0\" }\n",
    )
    .unwrap();
    fs::write(
        root.join("crates/core/Cargo.toml"),
        "[package]\nname = \"core\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    fs::write(root.join("crates/core/src/lib.rs"), "").unwrap();
    fs::write(
        root.join("crates/app/Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n[dependencies]\ncore = { workspace = true }\n",
    )
    .unwrap();
    fs::write(root.join("crates/app/src/lib.rs"), "").unwrap();
    fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"core\"\nversion = \"0.1.0\"\n\n[[package]]\nname = \"app\"\nversion = \"0.1.0\"\ndependencies = [\n \"core\",\n]\n",
    )
    .unwrap();
    write_patch_changeset(&root, "core");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let workspace = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(
        workspace.contains("core = { path = \"crates/core\", version = \"^0.1.1\" }"),
        "{workspace}"
    );
    let core = fs::read_to_string(root.join("crates/core/Cargo.toml")).unwrap();
    assert!(core.contains("version = \"0.1.1\""), "{core}");
    let app = fs::read_to_string(root.join("crates/app/Cargo.toml")).unwrap();
    assert!(app.contains("core = { workspace = true }"), "{app}");
    assert!(app.contains("version = \"0.1.0\""), "{app}");
    let lock = fs::read_to_string(root.join("Cargo.lock")).unwrap();
    assert!(
        lock.contains("name = \"core\"\nversion = \"0.1.1\""),
        "{lock}"
    );
}

#[test]
fn version_rewrites_package_and_workspace_table_in_the_same_file() {
    let root = temp_repo("pkg-ws-root");
    fs::create_dir_all(root.join("src")).unwrap();
    fs::create_dir_all(root.join("app/src")).unwrap();
    fs::write(
        root.join("Cargo.toml"),
        "[package]\nname = \"core\"\nversion = \"0.1.0\"\nedition = \"2021\"\n\n[workspace]\nresolver = \"2\"\nmembers = [\".\", \"app\"]\n[workspace.dependencies]\ncore = { path = \".\", version = \"^0.1.0\" }\n",
    )
    .unwrap();
    fs::write(root.join("src/lib.rs"), "").unwrap();
    fs::write(
        root.join("app/Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n[dependencies]\ncore = { workspace = true }\n",
    )
    .unwrap();
    fs::write(root.join("app/src/lib.rs"), "").unwrap();
    write_patch_changeset(&root, "core");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let toml = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    assert!(toml.contains("version = \"0.1.1\""), "{toml}");
    assert!(
        toml.contains("core = { path = \".\", version = \"^0.1.1\" }"),
        "{toml}"
    );
}

#[test]
fn version_retargets_a_published_range_on_the_dependent() {
    let root = temp_repo("published-range");
    fs::create_dir_all(root.join("crates/core/src")).unwrap();
    fs::create_dir_all(root.join("crates/app/src")).unwrap();
    fs::write(
        root.join("Cargo.toml"),
        "[workspace]\nresolver = \"2\"\nmembers = [\"crates/core\", \"crates/app\"]\n",
    )
    .unwrap();
    fs::write(
        root.join("crates/core/Cargo.toml"),
        "[package]\nname = \"core\"\nversion = \"0.1.0\"\nedition = \"2021\"\n",
    )
    .unwrap();
    fs::write(root.join("crates/core/src/lib.rs"), "").unwrap();
    fs::write(
        root.join("crates/app/Cargo.toml"),
        "[package]\nname = \"app\"\nversion = \"0.1.0\"\nedition = \"2021\"\n[dependencies]\ncore = { path = \"../core\", version = \"^0.1.0\" }\n",
    )
    .unwrap();
    fs::write(root.join("crates/app/src/lib.rs"), "").unwrap();
    write_patch_changeset(&root, "core");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let app = fs::read_to_string(root.join("crates/app/Cargo.toml")).unwrap();
    assert!(
        app.contains("core = { path = \"../core\", version = \"^0.1.1\" }"),
        "{app}"
    );
    assert!(app.contains("version = \"0.1.0\""), "{app}");
}

#[test]
fn unretargetable_lockfile_leaves_manifests_untouched() {
    let root = temp_repo("bad-lock");
    cargo_package(&root, "demo");
    let before = fs::read_to_string(root.join("Cargo.toml")).unwrap();
    fs::write(
        root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\npackage = 4\n",
    )
    .expect("lock");
    write_patch_changeset(&root, "demo");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        !output.status.success(),
        "expected lock retarget to fail: {}",
        String::from_utf8_lossy(&output.stdout)
    );
    assert_eq!(fs::read_to_string(root.join("Cargo.toml")).unwrap(), before);
    assert_eq!(
        fs::read_to_string(root.join("Cargo.lock")).unwrap(),
        "# This file is automatically @generated by Cargo.\nversion = 4\npackage = 4\n"
    );
}

#[test]
fn version_bumps_an_npm_package_json() {
    let root = temp_repo("npm");
    fs::write(
        root.join("package.json"),
        "{\n  \"name\": \"demo\",\n  \"version\": \"0.1.0\"\n}\n",
    )
    .expect("package.json");
    write_patch_changeset(&root, "demo");

    let output = bin()
        .current_dir(&root)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let json = fs::read_to_string(root.join("package.json")).unwrap();
    assert!(json.contains("\"version\": \"0.1.1\""), "{json}");
}

#[test]
fn version_retargets_the_cargo_lock_under_the_workspace_root() {
    let root = temp_repo("nested-lock");
    let rust = root.join("rust");
    fs::create_dir_all(&rust).expect("rust");
    cargo_package(&rust, "demo");
    fs::write(
        rust.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\nversion = 4\n\n[[package]]\nname = \"demo\"\nversion = \"0.1.0\"\n",
    )
    .expect("lock");
    fs::write(
        root.join("Cargo.lock"),
        "# decoy\nversion = 4\n\n[[package]]\nname = \"demo\"\nversion = \"9.9.9\"\n",
    )
    .expect("decoy");
    write_patch_changeset(&root, "demo");

    let output = bin()
        .current_dir(&rust)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let lock = fs::read_to_string(rust.join("Cargo.lock")).unwrap();
    assert!(
        lock.contains("name = \"demo\"\nversion = \"0.1.1\""),
        "{lock}"
    );
    let decoy = fs::read_to_string(root.join("Cargo.lock")).unwrap();
    assert!(decoy.contains("version = \"9.9.9\""), "{decoy}");
}

#[test]
fn version_bumps_a_nested_npm_package_json() {
    let root = temp_repo("nested-npm");
    let pkg = root.join("packages/demo");
    fs::create_dir_all(&pkg).expect("packages/demo");
    fs::write(
        pkg.join("package.json"),
        "{\n  \"name\": \"demo\",\n  \"version\": \"0.1.0\"\n}\n",
    )
    .expect("package.json");
    fs::write(
        root.join("package.json"),
        "{\n  \"name\": \"decoy\",\n  \"version\": \"9.9.9\"\n}\n",
    )
    .expect("decoy");
    write_patch_changeset(&root, "demo");

    let output = bin()
        .current_dir(&pkg)
        .arg("version")
        .output()
        .expect("run");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );
    let json = fs::read_to_string(pkg.join("package.json")).unwrap();
    assert!(json.contains("\"version\": \"0.1.1\""), "{json}");
    let decoy = fs::read_to_string(root.join("package.json")).unwrap();
    assert!(decoy.contains("\"version\": \"9.9.9\""), "{decoy}");
}
