#!/usr/bin/env bash
# Cursor / Claude worktree bootstrap for oakum.
# Runs once when Cursor creates a worktree (see .cursor/worktrees.json).
set -euo pipefail

ROOT="${ROOT_WORKTREE_PATH:-}"
if [[ -z "$ROOT" ]]; then
  echo "ROOT_WORKTREE_PATH is unset; refusing to guess the main checkout." >&2
  exit 1
fi
if [[ ! -d "$ROOT" ]]; then
  echo "ROOT_WORKTREE_PATH is not a directory: $ROOT" >&2
  exit 1
fi

ROOT=$(cd "$ROOT" && pwd)
if ! git rev-parse --git-common-dir >/dev/null 2>&1; then
  echo "must run from inside an oakum git worktree (cwd is not a checkout)." >&2
  exit 1
fi
GIT_COMMON=$(cd "$(git rev-parse --git-common-dir)" && pwd)
MAIN=$(cd "$(dirname "$GIT_COMMON")" && pwd)
if [[ "$ROOT" != "$MAIN" ]]; then
  echo "ROOT_WORKTREE_PATH must be this repo's main checkout ($MAIN), not: $ROOT" >&2
  exit 1
fi
if [[ ! -f "$ROOT/Cargo.toml" || ! -f "$ROOT/.mise.toml" ]]; then
  echo "ROOT_WORKTREE_PATH does not look like the oakum checkout: $ROOT" >&2
  exit 1
fi

# Encode for a TOML basic string. Refuse control characters (invalid in TOML strings).
toml_basic_string() {
  local s=$1
  if [[ "$s" =~ [[:cntrl:]] ]]; then
    echo "path contains control characters; refusing to write Cargo config: $s" >&2
    return 1
  fi
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  printf '"%s"' "$s"
}

# Per-worktree target under the main checkout: shares disk root with main but
# avoids one global Cargo lock / CARGO_TARGET_TMPDIR collision across agents.
WT_NAME=$(basename "$(pwd)")
TARGET_DIR="$ROOT/target/wt-${WT_NAME}"
mkdir -p "$TARGET_DIR" .cargo
TARGET_TOML=$(toml_basic_string "$TARGET_DIR")
cat >.cargo/config.toml <<EOF
# Generated by .cursor/setup-worktree-unix.sh — gitignored; do not commit.
[build]
target-dir = ${TARGET_TOML}
EOF

# Pin the same toolchain the main checkout uses.
mise install

SETUP_OK=1
# Soft-fail: Dolt may be briefly unreachable; cargo work still proceeds.
if ! mise run setup; then
  SETUP_OK=0
  echo "warning: mise run setup incomplete (often bd remote unreachable)." >&2
fi

if [[ "$SETUP_OK" -eq 1 ]]; then
  echo "oakum worktree ready (CARGO target-dir → $TARGET_DIR)"
else
  echo "oakum worktree: target-dir set ($TARGET_DIR); mise run setup incomplete — run it before relying on beads hooks." >&2
fi
