//! `version` owns changelog bytes (ADR-0023 / ADR-0031).
//!
//! Default emit is the genre intersection: date in the version heading, blanks
//! around headings and lists, no HTML, no italic-only date line, one trailing
//! newline. Notes stay verbatim. A configured `template` renders one version
//! section; the file envelope (`# Changelog`, footer, splice) stays here.

use std::collections::BTreeMap;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

use cap_std::fs::Dir;
use oakum::plan::{
    AggregatedBump, BumpLevel, ChangeSource, Ecosystem, Package, PackageId, Plan, PlannedChange,
    Workspace,
};
use oakum::template;
use semver::Version;
use serde::Serialize;

use super::inherited::read_text;
use super::write_set::PlannedWrite;
use super::CliError;

const CHANGELOG_NAME: &str = "CHANGELOG.md";
const TITLE: &str = "# Changelog";
const FOOTER_PREFIX: &str = "Generated by oakum ";

pub(super) struct ChangelogPlan<'a> {
    date: &'a str,
    tool_version: &'a str,
    template: Option<&'a str>,
    supplied_notes: Option<&'a str>,
}

impl<'a> ChangelogPlan<'a> {
    pub(super) fn new(
        date: &'a str,
        tool_version: &'a str,
        template: Option<&'a str>,
        supplied_notes: Option<&'a str>,
    ) -> Self {
        Self {
            date,
            tool_version,
            template,
            supplied_notes,
        }
    }
}

/// # Errors
///
/// Clock before the Unix epoch.
pub(super) fn utc_date(now: SystemTime) -> Result<String, Box<dyn std::error::Error>> {
    let secs = now
        .duration_since(UNIX_EPOCH)
        .map_err(|_| CliError::new("system clock is before the Unix epoch"))?
        .as_secs();
    Ok(ymd_from_unix_days(secs / 86_400))
}

/// # Errors
///
/// Missing workspace package, template render failure, or a file oakum cannot splice.
pub(super) fn plan_changelog_writes(
    dir: &Dir,
    workspace: &Workspace,
    plan: &Plan,
    intent: &BTreeMap<PackageId, AggregatedBump>,
    input: &ChangelogPlan<'_>,
) -> Result<Vec<PlannedWrite>, Box<dyn std::error::Error>> {
    let mut sections_by_path: BTreeMap<PathBuf, Vec<String>> = BTreeMap::new();
    for change in plan.changes().values() {
        let package = workspace.get(change.id()).ok_or_else(|| {
            CliError::new(format!(
                "{} is in the plan but not in the workspace",
                change.id().name
            ))
        })?;
        let section = emit_section(package, change, intent.get(change.id()), plan, input)?;
        sections_by_path
            .entry(changelog_path(package))
            .or_default()
            .push(section);
    }

    let mut writes = Vec::new();
    for (path, sections) in sections_by_path {
        match read_text(dir, &path)? {
            None => {
                let next = assemble_new(&sections, input.tool_version);
                writes.push(PlannedWrite::create(path, next));
            }
            Some(original) => {
                let next = splice(&path, &original, &sections, input.tool_version)?;
                writes.push(PlannedWrite::new(path, original, next));
            }
        }
    }
    Ok(writes)
}

fn changelog_path(package: &Package) -> PathBuf {
    let dir = package.manifest_dir();
    if dir.is_empty() {
        PathBuf::from(CHANGELOG_NAME)
    } else {
        Path::new(dir).join(CHANGELOG_NAME)
    }
}

fn emit_section(
    package: &Package,
    change: &PlannedChange,
    bump: Option<&AggregatedBump>,
    plan: &Plan,
    input: &ChangelogPlan<'_>,
) -> Result<String, Box<dyn std::error::Error>> {
    let notes = match input.supplied_notes {
        Some(body) => supplied_note(body).into_iter().collect(),
        None => release_notes(bump),
    };
    if let Some(source) = input.template {
        return render_template(source, package, change, &notes, input);
    }
    if input.supplied_notes.is_some() {
        return Ok(supplied_section(
            change.to(),
            input.date,
            notes.first().copied(),
        ));
    }
    Ok(builtin_section(
        change.to(),
        input.date,
        bump,
        cascade_attribution(change, plan)?,
    ))
}

fn cascade_attribution<'a>(
    change: &'a PlannedChange,
    plan: &'a Plan,
) -> Result<Option<(&'a str, &'a Version)>, CliError> {
    match change.source() {
        ChangeSource::Intent => Ok(None),
        ChangeSource::Cascade { trigger } => {
            let Some(trigger_change) = plan.get(trigger) else {
                return Err(CliError::new(format!(
                    "{} cascaded from {trigger} but that package is not in the plan",
                    change.id()
                )));
            };
            Ok(Some((trigger.name.as_str(), trigger_change.to())))
        }
    }
}

fn supplied_section(version: &Version, date: &str, body: Option<&str>) -> String {
    match body {
        Some(body) => format!("## {version} ({date})\n\n{body}\n"),
        None => format!("## {version} ({date})\n"),
    }
}

fn builtin_section(
    version: &Version,
    date: &str,
    bump: Option<&AggregatedBump>,
    cascade: Option<(&str, &Version)>,
) -> String {
    let mut out = format!("## {version} ({date})\n");
    let [(added_h, added), (changed_h, mut changed), (fixed_h, fixed)] = grouped_notes(bump);
    let cascade_line = cascade.map(|(name, to)| format!("Updated {name} to {to}"));
    if let Some(line) = cascade_line.as_deref() {
        changed.push(line);
    }
    for (heading, notes) in [(added_h, added), (changed_h, changed), (fixed_h, fixed)] {
        if notes.is_empty() {
            continue;
        }
        out.push('\n');
        out.push_str("### ");
        out.push_str(heading);
        out.push_str("\n\n");
        out.push_str(&notes.join("\n\n"));
        out.push('\n');
    }
    out
}

fn grouped_notes(bump: Option<&AggregatedBump>) -> [(&'static str, Vec<&str>); 3] {
    let mut added = Vec::new();
    let mut changed = Vec::new();
    let mut fixed = Vec::new();
    if let Some(bump) = bump {
        for contribution in bump.contributions() {
            let Some(note) = note_body(contribution.note()) else {
                continue;
            };
            if !contribution.level().is_release() {
                continue;
            }
            match contribution.level() {
                BumpLevel::Minor => added.push(note),
                BumpLevel::Major => changed.push(note),
                BumpLevel::Patch => fixed.push(note),
                BumpLevel::None => {}
            }
        }
    }
    [("Added", added), ("Changed", changed), ("Fixed", fixed)]
}

fn release_notes(bump: Option<&AggregatedBump>) -> Vec<&str> {
    let Some(bump) = bump else {
        return Vec::new();
    };
    bump.notes().filter_map(note_body).collect()
}

fn note_body(note: &str) -> Option<&str> {
    let note = note.trim_matches(['\n', '\r']);
    if note.is_empty() {
        None
    } else {
        Some(note)
    }
}

pub(super) fn supplied_note(body: &str) -> Option<&str> {
    let body = body.trim_end_matches(['\n', '\r']);
    if body.is_empty() {
        None
    } else {
        Some(body)
    }
}

#[derive(Serialize)]
struct SectionContext<'a> {
    version: String,
    date: &'a str,
    notes: Vec<&'a str>,
    package: &'a str,
    ecosystem: &'a str,
    bump: String,
    source: &'a str,
    trigger: Option<&'a str>,
    tool_version: &'a str,
    target: &'static str,
}

fn render_template(
    source: &str,
    package: &Package,
    change: &PlannedChange,
    notes: &[&str],
    input: &ChangelogPlan<'_>,
) -> Result<String, Box<dyn std::error::Error>> {
    let (source_kind, trigger) = match change.source() {
        ChangeSource::Intent => ("intent", None),
        ChangeSource::Cascade { trigger } => ("cascade", Some(trigger.name.as_str())),
    };
    let rendered = template::render(
        "changelog",
        source,
        SectionContext {
            version: change.to().to_string(),
            date: input.date,
            notes: notes.to_vec(),
            package: package.id().name.as_str(),
            ecosystem: ecosystem_label(package.id().ecosystem),
            bump: change.applied().effective().to_string(),
            source: source_kind,
            trigger,
            tool_version: input.tool_version,
            target: "changelog",
        },
    )
    .map_err(|err| CliError::new(err.to_string()))?;
    let mut rendered = rendered.trim_start_matches('\u{FEFF}').to_owned();
    if !rendered.ends_with('\n') {
        rendered.push('\n');
    }
    Ok(rendered)
}

fn ecosystem_label(ecosystem: Ecosystem) -> &'static str {
    match ecosystem {
        Ecosystem::Cargo => "cargo",
        Ecosystem::Npm => "npm",
    }
}

fn assemble_new(sections: &[String], tool_version: &str) -> String {
    let footer = format!("{FOOTER_PREFIX}{tool_version}.");
    join_blocks(&[TITLE, &sections.join("\n"), &footer])
}

fn splice(
    path: &Path,
    existing: &str,
    sections: &[String],
    tool_version: &str,
) -> Result<String, Box<dyn std::error::Error>> {
    if existing.starts_with('\u{FEFF}') {
        return Err(Box::new(CliError::new(format!(
            "{} starts with a UTF-8 BOM; oakum will not splice a changelog it cannot recognize",
            path.display()
        ))));
    }
    if !starts_with_title(existing) {
        return Err(Box::new(CliError::new(format!(
            "{} does not start with `{TITLE}`; oakum will not append without a recognized heading",
            path.display()
        ))));
    }
    let body = strip_oakum_footer(existing);
    let new_sections = sections.join("\n");
    let footer = format!("{FOOTER_PREFIX}{tool_version}.");
    match version_heading_start(body) {
        Some(at) => {
            let prefix = &body[..at];
            let rest = &body[at..];
            Ok(join_blocks(&[prefix, &new_sections, rest, &footer]))
        }
        None => Ok(join_blocks(&[body, &new_sections, &footer])),
    }
}

fn starts_with_title(text: &str) -> bool {
    let Some(rest) = text.strip_prefix(TITLE) else {
        return false;
    };
    rest.is_empty() || rest.starts_with('\n') || rest.starts_with("\r\n")
}

fn strip_oakum_footer(text: &str) -> &str {
    let trimmed = text.trim_end_matches(['\n', '\r']);
    let Some((rest, last)) = trimmed.rsplit_once('\n') else {
        return if is_oakum_footer(trimmed) {
            ""
        } else {
            trimmed
        };
    };
    let last = last.trim_end_matches('\r');
    if is_oakum_footer(last) {
        rest.trim_end_matches(['\n', '\r'])
    } else {
        trimmed
    }
}

fn is_oakum_footer(line: &str) -> bool {
    line.strip_prefix(FOOTER_PREFIX)
        .and_then(|rest| rest.strip_suffix('.'))
        .is_some_and(|version| Version::parse(version).is_ok())
}

fn version_heading_start(text: &str) -> Option<usize> {
    let mut pos = 0;
    for line in text.split_inclusive('\n') {
        let content = line.trim_end_matches(['\n', '\r']);
        if is_version_heading(content) {
            return Some(pos);
        }
        pos += line.len();
    }
    None
}

fn is_version_heading(line: &str) -> bool {
    let Some(rest) = line.strip_prefix("## ") else {
        return false;
    };
    heading_version(rest).is_some()
}

fn heading_version(rest: &str) -> Option<Version> {
    let rest = rest.trim_start_matches('[').trim_start_matches('v');
    let token = rest
        .split(|character: char| {
            character == ']' || character == ' ' || character == '(' || character == '-'
        })
        .next()
        .unwrap_or("");
    Version::parse(token).ok()
}

fn join_blocks(blocks: &[&str]) -> String {
    let mut out = String::new();
    for block in blocks {
        let block = block.trim_end_matches(['\n', '\r']);
        if block.is_empty() {
            continue;
        }
        if !out.is_empty() {
            out.push_str("\n\n");
        }
        out.push_str(block);
    }
    out.push('\n');
    out
}

fn ymd_from_unix_days(days: u64) -> String {
    let (year, month, day) = civil_from_days(days);
    format!("{year:04}-{month:02}-{day:02}")
}

/// Civil date from days since 1970-01-01 (Howard Hinnant).
fn civil_from_days(days: u64) -> (i32, u8, u8) {
    let z = i64::try_from(days).unwrap_or(i64::MAX) + 719_468;
    let era = z / 146_097;
    let doe = z - era * 146_097;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let mut year = yoe + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let day = doy - (153 * mp + 2) / 5 + 1;
    let month = if mp < 10 { mp + 3 } else { mp - 9 };
    if month <= 2 {
        year += 1;
    }
    (
        i32::try_from(year).unwrap_or(i32::MAX),
        u8::try_from(month).unwrap_or(u8::MAX),
        u8::try_from(day).unwrap_or(u8::MAX),
    )
}

#[cfg(test)]
mod tests {
    use super::{
        builtin_section, civil_from_days, join_blocks, splice, strip_oakum_footer, supplied_note,
        supplied_section, ymd_from_unix_days,
    };
    use oakum::plan::{aggregate, BumpFile, BumpLevel, Ecosystem, PackageId};
    use semver::Version;
    use std::path::Path;

    fn cargo(name: &str) -> PackageId {
        PackageId::new(Ecosystem::Cargo, name)
    }

    fn bump(note: &str, level: BumpLevel) -> oakum::plan::AggregatedBump {
        let intent = aggregate([BumpFile {
            id: String::from("one.md"),
            entries: vec![(cargo("demo"), level)],
            note: String::from(note),
        }]);
        intent.into_values().next().expect("bump")
    }

    #[test]
    fn civil_dates_match_known_unix_days() {
        assert_eq!(civil_from_days(0), (1970, 1, 1));
        assert_eq!(civil_from_days(10_957), (2000, 1, 1));
        assert_eq!(civil_from_days(19_993), (2024, 9, 27));
        assert_eq!(civil_from_days(20_690), (2026, 8, 25));
        assert_eq!(ymd_from_unix_days(20_690), "2026-08-25");
    }

    #[test]
    fn builtin_pins_heading_blank_section_blank_list() {
        let bump = bump("\npatch demo\n", BumpLevel::Patch);
        let section = builtin_section(&Version::new(0, 1, 1), "2026-08-25", Some(&bump), None);
        assert_eq!(
            section,
            "## 0.1.1 (2026-08-25)\n\n### Fixed\n\npatch demo\n"
        );
    }

    #[test]
    fn builtin_groups_notes_by_contribution_level() {
        let intent = aggregate([
            BumpFile {
                id: String::from("one.md"),
                entries: vec![(cargo("demo"), BumpLevel::Patch)],
                note: String::from("\npatch demo\n"),
            },
            BumpFile {
                id: String::from("two.md"),
                entries: vec![(cargo("demo"), BumpLevel::Minor)],
                note: String::from("\nminor demo\n"),
            },
        ]);
        let bump = intent.values().next().expect("bump");
        let section = builtin_section(&Version::new(0, 2, 0), "2026-08-25", Some(bump), None);
        assert_eq!(
            section,
            "## 0.2.0 (2026-08-25)\n\n### Added\n\nminor demo\n\n### Fixed\n\npatch demo\n"
        );
    }

    #[test]
    fn builtin_omits_empty_and_none_notes() {
        let intent = aggregate([BumpFile {
            id: String::from("one.md"),
            entries: vec![(cargo("demo"), BumpLevel::None)],
            note: String::from("\nno release\n"),
        }]);
        let bump = intent.values().next().expect("bump");
        let section = builtin_section(&Version::new(0, 1, 1), "2026-08-25", Some(bump), None);
        assert_eq!(section, "## 0.1.1 (2026-08-25)\n");
    }

    #[test]
    fn supplied_notes_replace_grouped_bump_notes() {
        assert_eq!(
            supplied_section(&Version::new(0, 1, 1), "2026-08-25", Some("workflow notes")),
            "## 0.1.1 (2026-08-25)\n\nworkflow notes\n"
        );
        assert_eq!(
            supplied_section(
                &Version::new(0, 1, 1),
                "2026-08-25",
                supplied_note("\n\nworkflow notes\n"),
            ),
            "## 0.1.1 (2026-08-25)\n\n\n\nworkflow notes\n"
        );
        assert_eq!(
            supplied_section(&Version::new(0, 1, 1), "2026-08-25", None),
            "## 0.1.1 (2026-08-25)\n"
        );
    }

    #[test]
    fn splice_new_file_is_genre_intersection() {
        let bump = bump("\npatch demo\n", BumpLevel::Patch);
        let section = builtin_section(&Version::new(0, 1, 1), "2026-08-25", Some(&bump), None);
        let next = super::assemble_new(&[section], "0.0.0");
        assert_eq!(
            next,
            "# Changelog\n\n## 0.1.1 (2026-08-25)\n\n### Fixed\n\npatch demo\n\nGenerated by oakum 0.0.0.\n"
        );
        assert!(!next.contains("<sub>"));
        assert!(!next.contains("\n\n\n"));
        assert!(next.ends_with('\n'));
        assert!(!next.ends_with("\n\n"));
    }

    #[test]
    fn splice_prepends_before_the_first_version_heading() {
        let existing = "# Changelog\n\n## [Unreleased]\n\n## 0.1.0 (2026-01-01)\n\n### Added\n\nold\n\nGenerated by oakum 0.0.0.\n";
        let section = "## 0.1.1 (2026-08-25)\n\n### Fixed\n\npatch demo\n";
        let next = splice(
            Path::new("CHANGELOG.md"),
            existing,
            &[section.to_owned()],
            "0.0.0",
        )
        .expect("splice");
        assert_eq!(
            next,
            "# Changelog\n\n## [Unreleased]\n\n## 0.1.1 (2026-08-25)\n\n### Fixed\n\npatch demo\n\n## 0.1.0 (2026-01-01)\n\n### Added\n\nold\n\nGenerated by oakum 0.0.0.\n"
        );
        let dated_unreleased = splice(
            Path::new("CHANGELOG.md"),
            "# Changelog\n\n## [Unreleased] - 2026-01-01\n\n## 0.1.0 (2026-01-01)\n",
            &[String::from("## 0.1.1 (2026-08-25)\n")],
            "0.0.0",
        )
        .expect("dated unreleased");
        assert!(
            dated_unreleased.starts_with(
                "# Changelog\n\n## [Unreleased] - 2026-01-01\n\n## 0.1.1 (2026-08-25)\n"
            ),
            "{dated_unreleased}"
        );
    }

    #[test]
    fn splice_refuses_a_file_without_the_title() {
        let err = splice(
            Path::new("crates/core/CHANGELOG.md"),
            "notes\n",
            &[String::from("## 0.1.1 (2026-08-25)\n")],
            "0.0.0",
        )
        .expect_err("refuse");
        assert!(
            err.to_string()
                .contains("crates/core/CHANGELOG.md does not start with `# Changelog`"),
            "{err}"
        );
        let blank = splice(
            Path::new("CHANGELOG.md"),
            "\n# Changelog\n",
            &[String::from("## 0.1.1 (2026-08-25)\n")],
            "0.0.0",
        )
        .expect_err("blank prefix");
        assert!(
            blank
                .to_string()
                .contains("does not start with `# Changelog`"),
            "{blank}"
        );
        let empty = splice(
            Path::new("CHANGELOG.md"),
            "",
            &[String::from("## 0.1.1 (2026-08-25)\n")],
            "0.0.0",
        )
        .expect_err("empty existing");
        assert!(
            empty
                .to_string()
                .contains("does not start with `# Changelog`"),
            "{empty}"
        );
    }

    #[test]
    fn builtin_keeps_indented_note_bytes() {
        let bump = bump("\n    fn foo() {}\n", BumpLevel::Patch);
        let section = builtin_section(&Version::new(0, 1, 1), "2026-08-25", Some(&bump), None);
        assert_eq!(
            section,
            "## 0.1.1 (2026-08-25)\n\n### Fixed\n\n    fn foo() {}\n"
        );
    }

    #[test]
    fn builtin_writes_a_changed_line_for_a_cascade() {
        let section = builtin_section(
            &Version::new(0, 1, 1),
            "2026-08-25",
            None,
            Some(("core", &Version::new(0, 2, 0))),
        );
        assert_eq!(
            section,
            "## 0.1.1 (2026-08-25)\n\n### Changed\n\nUpdated core to 0.2.0\n"
        );
    }

    #[test]
    fn splice_refuses_a_bom() {
        let err = splice(
            Path::new("CHANGELOG.md"),
            "\u{FEFF}# Changelog\n",
            &[String::from("## 0.1.1 (2026-08-25)\n")],
            "0.0.0",
        )
        .expect_err("bom");
        assert!(err.to_string().contains("BOM"), "{err}");
    }

    #[test]
    fn strip_footer_leaves_foreign_last_lines() {
        assert_eq!(
            strip_oakum_footer("body\nGenerated by oakum 1.2.3.\n"),
            "body"
        );
        assert_eq!(
            strip_oakum_footer("body\nGenerated by oakum contributors.\n"),
            "body\nGenerated by oakum contributors."
        );
        assert_eq!(
            strip_oakum_footer("body\nnot a footer\n"),
            "body\nnot a footer"
        );
    }

    #[test]
    fn join_blocks_skips_empty_and_ends_with_one_newline() {
        assert_eq!(
            join_blocks(&["# Changelog", "", "tail"]),
            "# Changelog\n\ntail\n"
        );
    }
}
