#!/usr/bin/env bash
# Portable oakum worktree bootstrap.
# Call from a linked worktree after create (any agent tool / manual git).
#
# Main checkout path (required for Cargo target-dir layout):
#   --root <path>            preferred
#   ROOT_WORKTREE_PATH       Cursor / some runners
#   else: derive from `git rev-parse --git-common-dir`
#
# Adapters (loaders only — this script is the behavior):
#   Cursor  → .cursor/worktrees.json (runs after Cursor creates a worktree)
#   Claude  → default `claude --worktree` / EnterWorktree / isolation:worktree,
#             then scripts/claude-ensure-worktree-setup.sh (SessionStart/CwdChanged).
#             Do not use WorktreeCreate for git; that hook replaces create and is
#             for non-git VCS (Claude docs).
set -euo pipefail

MARKER=".cargo/oakum-worktree-bootstrapped"

usage() {
  echo "usage: setup-worktree.sh [--root <main-checkout-path>]" >&2
  exit 2
}

phys() {
  (cd "$1" && pwd -P)
}

ROOT=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --root)
      [[ $# -ge 2 ]] || usage
      ROOT=$2
      shift 2
      ;;
    -h | --help)
      usage
      ;;
    *)
      echo "unknown argument: $1" >&2
      usage
      ;;
  esac
done

if [[ -z "$ROOT" && -n "${ROOT_WORKTREE_PATH:-}" ]]; then
  ROOT=$ROOT_WORKTREE_PATH
fi

if ! git rev-parse --git-common-dir >/dev/null 2>&1; then
  echo "must run from inside an oakum git worktree (cwd is not a checkout)." >&2
  exit 1
fi

GIT_COMMON=$(phys "$(git rev-parse --git-common-dir)")
MAIN=$(phys "$(dirname "$GIT_COMMON")")
TOPLEVEL=$(phys "$(git rev-parse --show-toplevel)")

if [[ -z "$ROOT" ]]; then
  ROOT=$MAIN
else
  if [[ ! -d "$ROOT" ]]; then
    echo "main checkout path is not a directory: $ROOT" >&2
    exit 1
  fi
  ROOT=$(phys "$ROOT")
fi

if [[ "$ROOT" != "$MAIN" ]]; then
  echo "main checkout must be this repo's main worktree ($MAIN), not: $ROOT" >&2
  exit 1
fi
if [[ ! -f "$ROOT/Cargo.toml" || ! -f "$ROOT/.mise.toml" ]]; then
  echo "main checkout does not look like oakum: $ROOT" >&2
  exit 1
fi

# Refuse the main checkout and any subdirectory of it (e.g. crates/).
if [[ "$TOPLEVEL" == "$ROOT" ]]; then
  echo "refusing to run in the main checkout; use from a linked worktree." >&2
  exit 1
fi

# Always bootstrap at the worktree root, even if cwd is a subdirectory.
cd "$TOPLEVEL"

# Encode for a TOML basic string. Refuse control characters (invalid in TOML strings).
toml_basic_string() {
  local s=$1
  if [[ "$s" =~ [[:cntrl:]] ]]; then
    echo "path contains control characters; refusing to write Cargo config: $s" >&2
    return 1
  fi
  s=${s//\\/\\\\}
  s=${s//\"/\\\"}
  printf '"%s"' "$s"
}

# Per-worktree target under the main checkout: shares disk root with main but
# avoids one global Cargo lock / CARGO_TARGET_TMPDIR collision across agents.
WT_NAME=$(basename "$TOPLEVEL")
TARGET_DIR="$ROOT/target/wt-${WT_NAME}"
mkdir -p "$TARGET_DIR" .cargo
TARGET_TOML=$(toml_basic_string "$TARGET_DIR")
cat >.cargo/config.toml <<EOF
# Generated by scripts/setup-worktree.sh — gitignored; do not commit.
[build]
target-dir = ${TARGET_TOML}
EOF

# Pin the same toolchain the main checkout uses. Fail closed before the success
# marker so Claude's ensure hook can retry after a failed install.
mise install

# Soft-fail: Dolt may be briefly unreachable; cargo work still proceeds.
SETUP_OK=1
if ! mise run setup; then
  SETUP_OK=0
  echo "warning: mise run setup incomplete (often bd remote unreachable)." >&2
fi

# Written only after mise install succeeds so a partial run is retried.
date -u +%Y-%m-%dT%H:%M:%SZ >"$MARKER"

if [[ "$SETUP_OK" -eq 1 ]]; then
  echo "oakum worktree ready (CARGO target-dir → $TARGET_DIR)"
else
  echo "oakum worktree: target-dir set ($TARGET_DIR); mise run setup incomplete — run it before relying on beads hooks." >&2
fi
